
FROM node:24.8.0-alpine3.21

WORKDIR /app

RUN chown node:node .

USER node

COPY --chown=node:node \
    package.json \
    package-lock.json \
    .npmrc \
    ./

## install dependencies
RUN npm install

COPY --chown=node:node . .

## install dependencies & build the package
RUN npm install && \
    npm run build

CMD ["npx", "vite", "--host"]
