
FROM python:3.13-alpine

WORKDIR /app

COPY requirements.txt .
RUN pip3 install -r requirements.txt

COPY src/ .

CMD ["gunicorn", "-k", "eventlet", "-w", "1", "-b", "0.0.0.0", "--access-logfile", "-", "main:app", "--config", "python:main"]
