
FROM python:3.13-alpine

WORKDIR /app

RUN apk add --no-cache gcc python3-dev musl-dev linux-headers

COPY requirements.txt .
RUN pip3 install -r requirements.txt

COPY src/ .

CMD ["python3", "main.py", "--debug"]
